services:
  mcp-sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_sqlserver
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped